@extends('base')

@section('content')
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

    <div class="box-form">
      <div class="left">
        <div class="overlay">
          <h1>S.P.M.</h1>
          <h2>Where teaching and learning come together</h2>
          <p>
            S.P.M. (students projects management) is an online web platform
            dedicated to the development of teaching activities that streamlines
            the time of evaluation of works.
          </p>
          <a href="about.html" class="navbar__links">About</a>
        </div>
      </div>

      <div class="right">
        <h5 id="login-title">Login</h5>
        <p>
          Authentication is based on the institutional accounts generated by the
          educational institution.
        </p>
        <form action="{{route('login')}}" method="post">
          <div class="inputs">
            @if ($errors->has('email'))
            <div class="alert alert-danger">{{$errors->first('email')}}</div> @endif
            <input name="email" type="email" class="form-control @if ($errors->has('email')) is-invalid @endif" placeholder="Email" value="{{old('email')}}">
            <br />
            @if ($errors->has('password'))
            <div class="alert alert-danger">{{$errors->first('password')}}</div> @endif
            <input name="password" type="password" class="form-control @if ($errors->has('password')) is-invalid @endif alert-danger" placeholder="Password">
          </div>
          <br /><br />

          <div class="remember-me--forget-password">
            <!-- Angular -->
            <label>
              <input class="checkbox" type="checkbox" name="item" />
              <span class="text-checkbox">Remember me</span>
            </label>
            <p>
              <a href="#" id="forgot-password" page="./ForgotPassword"
                >Forgot your password?</a
              >
            </p>
          </div>
          <button
            id="login-submit"
            type="submit"
            class="w-100 btn btn-lg btn-primary"
          >
            Login
          </button>
        </form>
      </div>
    </div>
    <script src="../js/login.js"></script>
    @endsection
